"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.InitAnimation = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
require("./InitAnimation.css");
const InitAnimation = ({ onEnter }) => {
    return ((0, jsx_runtime_1.jsx)("div", { className: "init-animation-container", children: (0, jsx_runtime_1.jsxs)("div", { className: "init-animation", children: [(0, jsx_runtime_1.jsx)("div", { className: "logo-container", children: (0, jsx_runtime_1.jsxs)("svg", { className: "oh-my-commit-logo", viewBox: "0 0 200 100", width: "128", height: "64", children: [(0, jsx_runtime_1.jsx)("g", { className: "letter-y", transform: "translate(40,50)", children: (0, jsx_runtime_1.jsx)("path", { d: "M-10,-15 L0,5 L10,-15\n                   M0,5 L0,20", stroke: "currentColor", strokeWidth: "4", strokeLinecap: "round", fill: "none" }) }), (0, jsx_runtime_1.jsx)("g", { className: "letter-a1", transform: "translate(80,50)", children: (0, jsx_runtime_1.jsx)("path", { d: "M-10,20 L0,-15 L10,20\n                   M-6,8 L6,8", stroke: "currentColor", strokeWidth: "4", strokeLinecap: "round", fill: "none" }) }), (0, jsx_runtime_1.jsx)("g", { className: "letter-a2", transform: "translate(120,50)", children: (0, jsx_runtime_1.jsx)("path", { d: "M-10,20 L0,-15 L10,20\n                   M-6,8 L6,8", stroke: "currentColor", strokeWidth: "4", strokeLinecap: "round", fill: "none" }) }), (0, jsx_runtime_1.jsx)("g", { className: "letter-c", transform: "translate(160,50)", children: (0, jsx_runtime_1.jsx)("path", { d: "M12,-15 \n                   A18 18 0 0 0 -8,-15\n                   A22 22 0 0 0 -8,15\n                   A18 18 0 0 0 12,15", stroke: "currentColor", strokeWidth: "4", strokeLinecap: "round", fill: "none" }) })] }) }), (0, jsx_runtime_1.jsx)("div", { className: "text-container", children: (0, jsx_runtime_1.jsx)("span", { className: "tagline", children: "Oh My Commit" }) }), (0, jsx_runtime_1.jsxs)("button", { className: "enter-button", onClick: onEnter, children: [(0, jsx_runtime_1.jsx)("i", { className: "codicon codicon-arrow-right" }), "Enter"] })] }) }));
};
exports.InitAnimation = InitAnimation;
