#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 运行 gen-toc
pnpm run gen-toc

# 获取配置文件中的文件列表
files=$(node -e "console.log(require('./.toc.config.json').files.join(' '))")
patterns=$(node -e "console.log(require('./.toc.config.json').patterns.join(' '))")

# 对于配置的具体文件
for file in $files; do
  if git diff --quiet --cached "$file" || git diff --quiet "$file"; then
    git add "$file"
  fi
done

# 对于 glob patterns
for pattern in $patterns; do
  for file in $(git ls-files "$pattern"); do
    if git diff --quiet --cached "$file" || git diff --quiet "$file"; then
      git add "$file"
    fi
  done
done
